OneToManyTask/OneToManyTask/Areas/AdminPanel/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OneToManyTask.Data;

namespace OneToManyTask.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class TableController : Controller
    {
        private readonly AppDbContext _context;
        public TableController(AppDbContext context)
        {
            _context = context;            
        }
        public async Task<IActionResult> Index()
        {
            var sliderImages = await _context.SliderImages
                .Where(m=>m.IsDeleted == false)
                .ToListAsync();
            return View(sliderImages);
        }
        public IActionResult Create()
        {
            return View();  
        }
    }
}

OneToManyTask/OneToManyTask/Areas/AdminPanel/Views/Table/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminPanel/Views/Shared/_AdminLayout.cshtml";
}
<div class="container mt-5" style="width:700px;margin-left: 260px;background-color:white;" >
    <div class="form-group">
        <label for="exampleInputPassword1">Enter Link</label> <br />
        <input type="text" class="form-control"  placeholder="Trying write something..." style="border:1px solid black;padding-left: 10px;"> <br />
    </div>
    <button class="btn btn-primary">Yarat</button>
    <button class="btn btn-danger">
        <a asp-area="AdminPanel" asp-controller="Table" asp-action="Index"> Back </a>
    </button>
</div>